### ISSUE TITLE
jp的dtb没有驱动tf卡槽

### ISSUE THREAD

**Issue by seacatwu** [HelloTheAsia/amlogic-s9xxx-armbian#2]
jp-tvbox的u-boot，无法使用tf卡，能否再修改看看

**Comment by HelloTheAsia** [comment]
这个很早就修复了.目前就6.1.43的蓝牙有问题.
![image](https://github.com/HelloTheAsia/amlogic-s9xxx-armbian/assets/26612794/81dc0109-395a-4d42-b534-07b566d0c0c1)

**Comment by seacatwu** [comment]
这个还是内置的emmc，不是外置的tf卡，你可以测试一下插卡是否可以识别

**Comment by HelloTheAsia** [comment]
你仔细看下我的截图,emmc我没标出来而已,有两个32g.我找了几个人测试都是正常的
<img width="1132" alt="image" src="https://github.com/HelloTheAsia/amlogic-s9xxx-armbian/assets/26612794/a4f2a22b-857b-4dc8-8e25-97ee5e516143">

**Comment by seacatwu** [comment]
谢谢，我重新再刷一遍看看

**Comment by seacatwu** [comment]
我发现刷来刷去，都没有tf卡了，刷到了istoreos也没有。
请问一下，rkdevtools刷的话，正常来说是不是可以恢复？
有没有什么其它应该注意的地方，我总觉得uboot还是什么东西有问题。
